// import 'package:grocery_admin_panel/model/product_model.dart';
// import 'package:grocery_admin_panel/utils/app_color.dart';
//
// final List<ProductModel> productList = [
//   const ProductModel(
//     id: 101,
//     name: 'Fresh Red Apple',
//     category: 'Fruits',
//     image: 'assets/images/peach2.png',
//     bgColor: AppColor.fruitRed,
//     stock: '150',
//     price: '\$4.99',
//     quantity: '1 dozen',
//     description: 'Crisp, sweet, and freshly harvested red apples packed with vitamins, fiber, and natural sweetness.',
//   ),
//   const ProductModel(
//     id: 102,
//     name: 'Organic Broccoli',
//     category: 'Vegetables',
//     image: 'assets/images/broccoli.png',
//     bgColor: AppColor.broccoli,
//     stock: '85',
//     price: '\$2.49',
//     quantity: '1 kg',
//     description: 'Fresh organic green broccoli crowns sourced directly from local organic farms. Rich in antioxidants and nutrients.',
//   ),
//   const ProductModel(
//     id: 103,
//     name: 'Fresh Cavendish Banana',
//     category: 'Fruits',
//     image: 'assets/images/pineapple.png',
//     bgColor: AppColor.beverageYellow,
//     stock: '200',
//     price: '\$1.99',
//     quantity: '1 dozen',
//     description: 'Naturally ripened sweet Cavendish bananas, an excellent source of potassium and instant energy.',
//   ),
//   const ProductModel(
//     id: 104,
//     name: 'Hass Avocado',
//     category: 'Fruits',
//     image: 'assets/images/avocado.png',
//     bgColor: AppColor.avocado,
//     stock: '45',
//     price: '\$3.80',
//     quantity: '2.0 lbs',
//     description: 'Creamy Hass avocados rich in healthy monounsaturated fats, perfect for salads, toast, and guacamole.',
//   ),
//   const ProductModel(
//     id: 105,
//     name: 'Seedless Green Grapes',
//     category: 'Fruits',
//     image: 'assets/images/grapes.png',
//     bgColor: AppColor.grapes,
//     stock: '60',
//     price: '\$5.20',
//     quantity: '500 g',
//     description: 'Juicy, plump seedless green grapes with a crisp bite and refreshing sweet-tart flavor.',
//   ),
//   const ProductModel(
//     id: 106,
//     name: 'Fresh Green Spinach',
//     category: 'Vegetables',
//     image: 'assets/images/pomegranate.png',
//     bgColor: AppColor.vegetableGreen,
//     stock: '70',
//     price: '\$1.80',
//     quantity: '1 bunch',
//     description: 'Farm-fresh leafy green spinach bunches loaded with iron, essential vitamins, and minerals.',
//   ),
//   const ProductModel(
//     id: 107,
//     name: 'Organic Red Tomato',
//     category: 'Vegetables',
//     image: 'assets/images/grapes.png',
//     bgColor: AppColor.pomegranate,
//     stock: '120',
//     price: '\$2.99',
//     quantity: '1 kg',
//     description: 'Vine-ripened organic red tomatoes, juicy and bursting with flavor for cooking, sauces, and fresh salads.',
//   ),
//   const ProductModel(
//     id: 108,
//     name: 'Fresh Whole Pineapple',
//     category: 'Fruits',
//     image: 'assets/images/pineapple.png',
//     bgColor: AppColor.pineapple,
//     stock: '35',
//     price: '\$3.99',
//     quantity: '1 pc',
//     description: 'Tropical whole pineapple with fragrant golden flesh, high in vitamin C and digestive enzymes.',
//   ),
//   const ProductModel(
//     id: 109,
//     name: 'Crisp Bell Pepper',
//     category: 'Vegetables',
//     image: 'assets/images/pomegranate.png',
//     bgColor: AppColor.locationGreen,
//     stock: '90',
//     price: '\$3.20',
//     quantity: '500 g',
//     description: 'Vibrant, crunchy bell peppers ideal for stir-fries, fajitas, roasting, or fresh crunchy snacking.',
//   ),
//   const ProductModel(
//     id: 110,
//     name: 'Sweet Orange',
//     category: 'Fruits',
//     image: 'assets/images/pomegranate.png',
//     bgColor: AppColor.peach,
//     stock: '140',
//     price: '\$4.50',
//     quantity: '1 kg',
//     description: 'Juicy, sunshine-sweet oranges that are easy to peel and brimming with immunity-boosting vitamin C.',
//   ),
// ];
