final List<Map<String, dynamic>> recentOrderList = [
  {
    'id': 1001,
    'name': 'Fresh Red Apple & Banana Combo',
    'customer': 'Sarah Johnson',
    'date': '22 Aug 2026',
    'status': 'Completed',
    'price': '\$45.00',
  },
  {
    'id': 1002,
    'name': 'Organic Broccoli & Vegetables',
    'customer': 'Michael Brown',
    'date': '22 Aug 2026',
    'status': 'Pending',
    'price': '\$28.50',
  },
  {
    'id': 1003,
    'name': 'Fresh Avocado Pack (5 pcs)',
    'customer': 'Emily Davis',
    'date': '21 Aug 2026',
    'status': 'Processing',
    'price': '\$32.00',
  },
  {
    'id': 1004,
    'name': 'Sweet Green Grapes & Berries',
    'customer': 'David Wilson',
    'date': '21 Aug 2026',
    'status': 'Completed',
    'price': '\$64.20',
  },
  {
    'id': 1005,
    'name': 'Whole Grain Bread & Fresh Milk',
    'customer': 'Jessica Taylor',
    'date': '20 Aug 2026',
    'status': 'Delivered',
    'price': '\$18.90',
  },
  {
    'id': 1006,
    'name': 'Exotic Fruit Basket',
    'customer': 'James Anderson',
    'date': '20 Aug 2026',
    'status': 'Completed',
    'price': '\$89.00',
  },
  {
    'id': 1007,
    'name': 'Organic Farm Fresh Eggs',
    'customer': 'Amanda Martinez',
    'date': '19 Aug 2026',
    'status': 'Cancelled',
    'price': '\$14.50',
  },
  {
    'id': 1008,
    'name': 'Dairy Milk & Cheddar Cheese',
    'customer': 'Robert Thomas',
    'date': '19 Aug 2026',
    'status': 'Completed',
    'price': '\$52.30',
  },
  {
    'id': 1009,
    'name': 'Green Spinach & Bell Peppers',
    'customer': 'Sophia White',
    'date': '18 Aug 2026',
    'status': 'Processing',
    'price': '\$22.80',
  },
  {
    'id': 1010,
    'name': 'Natural Honey & Almonds Jar',
    'customer': 'Daniel Clark',
    'date': '18 Aug 2026',
    'status': 'Completed',
    'price': '\$76.00',
  },
];