// import 'package:grocery_admin_panel/model/customer_model.dart';
//
// // List of 10 customer records
// final List<CustomerModel> customerList = [
//   const CustomerModel(
//     id: 1,
//     name: 'Eleanor Pena',
//     image: 'assets/images/profile.png',
//     onboardDate: '12 Jan 2024',
//     email: 'eleanor.pena@example.com',
//     phone: '+1 (555) 234-5678',
//   ),
//   const CustomerModel(
//     id: 2,
//     name: 'Ralph Edwards',
//     image: 'assets/images/profile.png',
//     onboardDate: '18 Jan 2024',
//     email: 'ralph.edwards@example.com',
//     phone: '+1 (555) 345-6789',
//   ),
//   const CustomerModel(
//     id: 3,
//     name: 'Savannah Nguyen',
//     image: 'assets/images/profile.png',
//     onboardDate: '02 Feb 2024',
//     email: 'savannah.nguyen@example.com',
//     phone: '+1 (555) 456-7890',
//   ),
//   const CustomerModel(
//     id: 4,
//     name: 'Courtney Henry',
//     image: 'assets/images/profile.png',
//     onboardDate: '14 Feb 2024',
//     email: 'courtney.henry@example.com',
//     phone: '+1 (555) 567-8901',
//   ),
//   const CustomerModel(
//     id: 5,
//     name: 'Darrell Steward',
//     image: 'assets/images/profile.png',
//     onboardDate: '28 Feb 2024',
//     email: 'darrell.steward@example.com',
//     phone: '+1 (555) 678-9012',
//   ),
//   const CustomerModel(
//     id: 6,
//     name: 'Annette Black',
//     image: 'assets/images/profile.png',
//     onboardDate: '05 Mar 2024',
//     email: 'annette.black@example.com',
//     phone: '+1 (555) 789-0123',
//   ),
//   const CustomerModel(
//     id: 7,
//     name: 'Floyd Miles',
//     image: 'assets/images/profile.png',
//     onboardDate: '19 Mar 2024',
//     email: 'floyd.miles@example.com',
//     phone: '+1 (555) 890-1234',
//   ),
//   const CustomerModel(
//     id: 8,
//     name: 'Kristin Watson',
//     image: 'assets/images/profile.png',
//     onboardDate: '25 Mar 2024',
//     email: 'kristin.watson@example.com',
//     phone: '+1 (555) 901-2345',
//   ),
//   const CustomerModel(
//     id: 9,
//     name: 'Cameron Williamson',
//     image: "assets/images/profile.png",
//     onboardDate: '08 Apr 2024',
//     email: 'cameron.williamson@example.com',
//     phone: '+1 (555) 012-3456',
//   ),
//   const CustomerModel(
//     id: 10,
//     name: 'Theresa Webb',
//     image: "assets/images/profile.png",
//     onboardDate: '22 Apr 2024',
//     email: 'theresa.webb@example.com',
//     phone: '+1 (555) 123-4567',
//   ),
// ];
